# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_spider', '0005_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_statistics_json', models.TextField(default='null', verbose_name='\u8bc4\u8bba\u7edf\u8ba1')),
                ('word_count_json', models.TextField(default='null', verbose_name='\u8bcd\u9891\u7edf\u8ba1')),
                ('sentiment_value_json', models.TextField(default='null', verbose_name='\u60c5\u611f\u503c\u7edf\u8ba1')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5206\u6790\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u5206\u6790\u7ed3\u675f\u65f6\u95f4')),
                ('state', models.CharField(choices=[('waiting', '\u7b49\u5f85\u5206\u6790'), ('running', '\u6b63\u5728\u5206\u6790'), ('successful', '\u5206\u6790\u6210\u529f'), ('failed', '\u5206\u6790\u5931\u8d25')], default='waiting', max_length=20, verbose_name='\u5206\u6790\u72b6\u6001')),
                ('ex_data', models.TextField(null=True, verbose_name='\u989d\u5916\u4fe1\u606f')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='news_spider.News', verbose_name='\u6240\u5c5e\u65b0\u95fb')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u5206\u6790\u7ed3\u679c',
                'verbose_name_plural': '\u65b0\u95fb\u5206\u6790\u7ed3\u679c',
            },
        ),
    ]
