# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisResult',
            new_name='AnalysisTask',
        ),
    ]
