# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyzer', '0004_auto_20170326_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistask',
            options={'ordering': ['-create_time'], 'verbose_name': '\u65b0\u95fb\u5206\u6790\u4efb\u52a1', 'verbose_name_plural': '\u65b0\u95fb\u5206\u6790\u4efb\u52a1'},
        ),
        migrations.AddField(
            model_name='analysistask',
            name='interaction_count',
            field=models.IntegerField(default=0, verbose_name='\u4e92\u52a8\u603b\u6570'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='keyword_statistics_json',
            field=models.TextField(default='null', verbose_name='\u5173\u952e\u8bcd\u7edf\u8ba1'),
        ),
    ]
