# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u6b63\u6587'),
        ),
    ]
