# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_spider', '0002_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.BigIntegerField(verbose_name='\u8bc4\u8bbaID')),
                ('comment_time', models.DateTimeField(verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('vote_count', models.IntegerField(default=0, verbose_name='\u8d5e\u6210\u6570\u91cf')),
                ('against_count', models.IntegerField(default=0, verbose_name='\u53cd\u5bf9\u6570\u91cf')),
                ('is_anonymous', models.BooleanField(verbose_name='\u662f\u5426\u533f\u540d')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='\u7528\u6237ID')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7528\u6237\u540d')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7528\u6237\u4f4d\u7f6e')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='\u5934\u50cf\u94fe\u63a5')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-comment_time'],
                'verbose_name': '\u65b0\u95fb\u8bc4\u8bba',
                'verbose_name_plural': '\u65b0\u95fb\u8bc4\u8bba',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_at'], 'verbose_name': '\u65b0\u95fb\u6761\u76ee', 'verbose_name_plural': '\u65b0\u95fb\u6761\u76ee'},
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_spider.News', verbose_name='\u6240\u5c5e\u65b0\u95fb\u6761\u76ee'),
        ),
    ]
