# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_spider', '0004_auto_20161205_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u6458\u8981'),
        ),
    ]
