# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_spider', '0005_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='province',
            field=models.CharField(choices=[('\u672a\u77e5', '\u672a\u77e5'), ('\u5317\u4eac', '\u5317\u4eac\u5e02'), ('\u5e7f\u4e1c', '\u5e7f\u4e1c\u7701'), ('\u5c71\u4e1c', '\u5c71\u4e1c\u7701'), ('\u6c5f\u82cf', '\u6c5f\u82cf\u7701'), ('\u6cb3\u5357', '\u6cb3\u5357\u7701'), ('\u4e0a\u6d77', '\u4e0a\u6d77\u5e02'), ('\u6cb3\u5317', '\u6cb3\u5317\u7701'), ('\u6d59\u6c5f', '\u6d59\u6c5f\u7701'), ('\u9999\u6e2f', '\u9999\u6e2f\u7279\u522b\u884c\u653f\u533a'), ('\u9655\u897f', '\u9655\u897f\u7701'), ('\u6e56\u5357', '\u6e56\u5357\u7701'), ('\u91cd\u5e86', '\u91cd\u5e86\u5e02'), ('\u798f\u5efa', '\u798f\u5efa\u7701'), ('\u5929\u6d25', '\u5929\u6d25\u5e02'), ('\u4e91\u5357', '\u4e91\u5357\u7701'), ('\u56db\u5ddd', '\u56db\u5ddd\u7701'), ('\u5e7f\u897f', '\u5e7f\u897f\u58ee\u65cf\u81ea\u6cbb\u533a'), ('\u5b89\u5fbd', '\u5b89\u5fbd\u7701'), ('\u6d77\u5357', '\u6d77\u5357\u7701'), ('\u6c5f\u897f', '\u6c5f\u897f\u7701'), ('\u6e56\u5317', '\u6e56\u5317\u7701'), ('\u5c71\u897f', '\u5c71\u897f\u7701'), ('\u8fbd\u5b81', '\u8fbd\u5b81\u7701'), ('\u53f0\u6e7e', '\u53f0\u6e7e\u7701'), ('\u9ed1\u9f99\u6c5f', '\u9ed1\u9f99\u6c5f\u7701'), ('\u5185\u8499\u53e4', '\u5185\u8499\u53e4\u81ea\u6cbb\u533a'), ('\u6fb3\u95e8', '\u6fb3\u95e8\u7279\u522b\u884c\u653f\u533a'), ('\u8d35\u5dde', '\u8d35\u5dde\u7701'), ('\u7518\u8083', '\u7518\u8083\u7701'), ('\u9752\u6d77', '\u9752\u6d77\u7701'), ('\u65b0\u7586', '\u65b0\u7586\u7ef4\u543e\u5c14\u81ea\u6cbb\u533a'), ('\u897f\u85cf', '\u897f\u85cf\u81ea\u6cbb\u533a'), ('\u5409\u6797', '\u5409\u6797\u7701'), ('\u5b81\u590f', '\u5b81\u590f\u56de\u65cf\u81ea\u6cbb\u533a')], default='\u672a\u77e5', max_length=20, verbose_name='\u6240\u5728\u7701\u4efd'),
        ),
    ]
